spring.application.name=ms-courierpyme-envios

# neon
spring.datasource.url=jdbc:postgresql://ep-wild-morning-aegmret4.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=http://localhost:3000

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/06c17780-fea1-442b-9f82-9c3e5224d664/v2.0

# El público esperado (sin espacios después de la coma y sin duplicar la línea)
spring.security.oauth2.resourceserver.jwt.audiences=api://e2b91943-82bc-4369-a4c5-151aa20c8f6c,e2b91943-82bc-4369-a4c5-151aa20c8f6c

# Logs de depuración
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.security=DEBUG